### ISSUE TITLE
Can't connect with Postman to Server on IBMi and local-instance

### ISSUE THREAD

**Issue by bashdi** [Mapepire-IBMi/mapepire-server#71]
Hello,
I'm trying to connect to mapepire-server with Postman and go-Code.

As a response i'm getting a http status code 404:

> Error: Unexpected server response: 404
Handshake Details
Request URL: http://localhost:8076/
Request Method: GET
Status Code: 404 Not Found
Request Headers
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: OHX/aXxTguwuxCHsSF6Orw==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: localhost:8076
Response Headers
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 510
Server: Jetty(9.4.54.v20240208)

go-Code tells me:

> ERROR websocket: bad handshake

Set env-var:

> MP_UNSECURE=true
DB_SERVER=192.xxx.xxxx.xxx (only set on my windows machine)

I tested the server on an IBMi 7.4 with Java 8 and 17, on Windows with Java 17.
mapepire-server Version 2.1.5

I'm currently not sure how to establish a websocket connect to the server.

**Comment by worksofliam** [comment]
@bashdi Are you able to connect with one of our clients? Perhaps you could try mapepire-js?

**Comment by bashdi** [comment]
Solved it.
Frist i trageted the **wrong entrypoint** with `localhost:8076/`, the right entrypoint is `localhost:8076/db/`
and second **Basic-Auth was missing**.
