### ISSUE TITLE
Implementing Mapepire-server on AIX with Python Client on AIX?

### ISSUE THREAD

**Issue by kraudy** [Mapepire-IBMi/mapepire-server#78]
The server i'm using does not have the mapepire repo on the repo.d directory and i don't have authorization to create it. So i need a workaround.

I can not do a ```wget``` download from github because it is blocked.

A little check on pub400 showed that mapepire it is indeed on an ibmi-base repo.
![image](https://github.com/user-attachments/assets/a69c134f-e808-4641-ba76-446e83786226)

So, now my move is  to go to the repo (https://public.dhe.ibm.com/software/ibmi/products/pase/rpms/repo-base-7.3/noarch/), download mapepire-server and the upload it AIX 

After that, i'll ask someone with authority to run the ``` yum install ./mapepire-server-x.x.noarch.rpm`` 

is there another dependency that i need to add or something that i'm missing so that i only ask once for the favor?

Thanks in advance.

Note: i know the docs (https://mapepire-ibmi.github.io/guides/sysadmin/) use Service Commander for the manual installation but i can not use that route unless i also manually install it

**Comment by kraudy** [comment]
Well, i jumped the yum part and ran the jar directly. Now, i'm trying to implement the Python client, but i get this error

![image](https://github.com/user-attachments/assets/316f2c4c-96b4-463a-904e-74983b72bc73)

this is the server output
![image](https://github.com/user-attachments/assets/dc4f518a-9c82-4988-8e06-6052d02a7207)


Any advice?

**Comment by jonnyz32** [comment]
It looks like the server was started successfully, but it can't find the value for hostname. Did you specify all the variables in your .ini file? When you run the client with a debugger, is the creds variable containing the right values? @ajshedivy

**Comment by kraudy** [comment]
@jonnyz32 
This is the .ini file

![image](https://github.com/user-attachments/assets/d0af1b6d-d26f-43d7-9865-d751a442ad3e)

**Comment by kraudy** [comment]
I got it to work

![image](https://github.com/user-attachments/assets/9430a8ce-54a2-4b1a-bdbb-8ae7b1a58131)

This is how the ini file should look
![image](https://github.com/user-attachments/assets/a026d189-049e-404d-84e3-85d932291d95)

**Comment by jonnyz32** [comment]
Glad you got it working! I will close this issue then.
