### ISSUE TITLE
Java 11 for SSL Handshake error

### ISSUE THREAD

**Issue by GautierFR** [Mapepire-IBMi/mapepire-server#79]
I meet a problem with SSL Handshake with different mapepire clients on my Windows 11 Station. 
For example with Python :` RuntimeError: An error occurred while connecting to the server: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)`
With ts :
```
Error: 0C470000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1586:SSL alert number 40
. Please ensure the Mapepire server is being run with Java version >= 11.
```

I get this type of error in any test I play (ts sample, python sample and js test) which shows an incompatibility in the TLS levels between the client and the server.

To resolve this, I install `opendjdk-11-ea` on the server side and change the file `/QOpenSys/pkgs/bin/mapepire` and change the line to call java 11. 

```
#!/QOpenSys/usr/bin/sh
exec /QOpenSys/pkgs/lib/jvm/openjdk-11/bin/java -Xsoftmx1G -Xmx16g -Xms256M -jar $(/QOpenSys/usr/bin/dirname $0)/../lib/mapepire/mapepire-server.jar
```

The text of error "Please ensure the Mapepire server is being run with Java version >= 11."  on the client side gives good indications. But maybe the documentation could provide some guidance on this subject.

**Comment by jonnyz32** [comment]
Possible solutions currently under discussion at the PR above
